branches:
  - "main"
  - name: "v3.x"
    prerelease: beta

preset: "conventionalcommits"


plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "semantic-release-cargo"
    - allFeatures: true
      check: true
      publishArgs: [ "-p", "lcax_core" ]
  - - "semantic-release-cargo"
    - allFeatures: false
      check: true
      publishArgs: [ "-p", "lcax_models" ]
  - - "semantic-release-cargo"
    - allFeatures: false
      check: true
      publishArgs: [ "-p", "lcax_calculation" ]
  - - "semantic-release-cargo"
    - allFeatures: false
      check: true
      publishArgs: [ "-p", "lcax_convert" ]
  - - "semantic-release-cargo"
    - allFeatures: false
      check: true
      publishArgs: [ "-p", "lcax_validation" ]
  - - "semantic-release-cargo"
    - allFeatures: false
      check: true
      publishArgs: [ "-p", "lcax" ]
  - - "@semantic-release/github"
    - assets:
        - { path: 'artifacts/lcax.schema.json', label: 'LCAx JSON Schema' }
        - { path: 'artifacts/validation.schema.json', label: 'LCAx Validation Schema' }
  - - "@semantic-release/git"
    - assets:
        - "CHANGELOG.md"
        - "Cargo.toml"
        - "Cargo.lock"
