branches:
  - "main"
  - name: "v3.0"
    prerelease: beta

preset: "conventionalcommits"


plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "semantic-release-cargo"
    - allFeatures: true
      check: true
      publishArgs: [ "-p", "lcax_core" ]
  - - "semantic-release-cargo"
    - allFeatures: false
      check: true
      publishArgs: [ "-p", "lcax_models" ]
  - - "semantic-release-cargo"
    - allFeatures: false
      check: true
      publishArgs: [ "-p", "lcax_calculation" ]
  - - "semantic-release-cargo"
    - allFeatures: false
      check: true
      publishArgs: [ "-p", "lcax_convert" ]
  - - "semantic-release-cargo"
    - allFeatures: false
      check: true
      publishArgs: [ "-p", "lcax_validation" ]
  - - "semantic-release-cargo"
    - allFeatures: false
      check: true
      publishArgs: [ "-p", "lcax" ]
  - - "@semantic-release/github"
    - assets:
        - { path: 'artifacts/lcax.schema.json', label: 'LCAx JSON Schema' }
#        - { path: 'packages/python/src/lcax/pydantic.py', label: 'LCAx Python Classes' }
#        - { path: 'artifacts/lcax.d.ts', label: 'LCAx TypeScript Declarations' }
        - { path: 'artifacts/project.rs', label: 'LCAx Rust Structs' }
#        - { path: 'artifacts/lcax.cs', label: 'LCAx C# Classes' }
  - - "@semantic-release/git"
    - assets:
        - "CHANGELOG.md"
        - "Cargo.toml"
        - "Cargo.lock"
