/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const convertLCAbyg: (a: number, b: number, c: number, d: number) => [number, number, number];
export const toLCAbyg: (a: any) => [number, number, number, number];
export const convertBRStandard: (a: number, b: number, c: number, d: number) => [number, number, number];
export const convertIlcd: (a: number, b: number) => [number, number, number];
export const calculateProject: (a: any) => [number, number, number];
export const calculateAssembly: (a: any, b: any) => [number, number, number];
export const calculateProduct: (a: any, b: any) => [number, number, number];
export const getImpactTotal: (a: any, b: any, c: number, d: number) => [number, number, number];
export const normalizeResult: (a: number, b: number) => [number, number, number];
export const getImpactsByLifeCycleModule: (a: any, b: any, c: number, d: number, e: number, f: number) => [number, number, number];
export const validate: (a: any, b: number, c: number) => [number, number, number, number];
export const projectPhases: () => [number, number];
export const roofTypes: () => [number, number];
export const generalEnergyClasses: () => [number, number];
export const buildingModelScopes: () => [number, number];
export const buildingTypes: () => [number, number];
export const buildingTypologies: () => [number, number];
export const standards: () => [number, number];
export const subTypes: () => [number, number];
export const lifeCycleModules: () => [number, number];
export const impactCategories: () => [number, number];
export const units: () => [number, number];
export const countries: () => [number, number];
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
