name: "Build Rust"

on:
  workflow_call:


jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Run Format
        run: cargo fmt --all -- --check

      - name: Run Tests
        run: cargo test --target x86_64-unknown-linux-gnu

      - name: Export LCAx Schema
        run: cargo run --target x86_64-unknown-linux-gnu --package lcax --bin export-schema > lcax.schema.json

      - name: Export Validation Schema
        run: cargo run --target x86_64-unknown-linux-gnu --package lcax_validation --bin export-schema > validation.schema.json

      - name: Upload JSON Schema
        uses: actions/upload-artifact@v4
        with:
          name: json-schema
          path: 'lcax.schema.json'

      - name: Upload Validation Schema
        uses: actions/upload-artifact@v4
        with:
          name: validation-schema
          path: 'validation.schema.json'
