name: Build JavaScript

on:
  workflow_call:

env:
  NODE_VERSION: '20.x'

jobs:
  build:
    name: Build JavaScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jetli/wasm-pack-action@v0.4.0

      - name: Build
        run: |
          wasm-pack build --features jsbindings
          mv pkg/lcax* packages/javascript/src

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        working-directory: 'packages/javascript'
        run: npm ci

      - name: Run Tests
        working-directory: 'packages/javascript'
        run: npm run test

      - name: Upload Generated Files
        uses: actions/upload-artifact@v4
        with:
          name: typescript-schema
          path: 'packages/javascript/src/lcax*'