name: Build NPM Package

on:
  workflow_call:

jobs:
  buildJavaScript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: json-schema
          path: packages/javascript

      - uses: actions/setup-node@v3
        name: Setup Node

      - name: Install Dependencies
        run: npm install json-schema-to-typescript --save

      - name: Create Typescript
        run: npx json2ts packages/javascript/lcax.schema.json packages/javascript/lcax.d.ts

      - name: Upload TypeScript
        uses: actions/upload-artifact@v3
        with:
          name: typescript-schema
          path: 'packages/javascript/lcax.d.ts'
