name: Publish PyPI Package

on:
  workflow_call:
    secrets:
      pypi_token:
        required: true
    inputs:
      release_version:
        required: false
        type: string
        default: ""

jobs:
  buildPython:
    if: ${{ inputs.release_version != ''}}
    runs-on: ${{ matrix.os.runner }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os:
          - name: linux-amd64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - name: win-amd64
            runner: windows-latest
            target: x86_64-pc-windows-msvc
          - name: macos-amd64
            runner: macos-latest
            target: x86_64-apple-darwin
          - name: macos-arm64
            runner: macos-latest
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: cargo

      - uses: actions/download-artifact@v4
        with:
          name: pydantic-schema
          path: packages/python/src/lcax

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install Dependencies
        run: |
          pip install maturin virtualenv
          virtualenv venv
          source venv/bin/activate
          maturin develop --target ${{ matrix.os.target }}

      - name: Build Wheel
        run: |
          source venv/bin/activate
          maturin build --target ${{ matrix.os.target }} --out dist

      - name: Upload Wheel
        uses: actions/upload-artifact@v4
        with:
          name: lcax-${{ matrix.os.name }}-${{ matrix.python-version }}
          path: dist

  publishPython:
    if: ${{ inputs.release_version != ''}}
    runs-on: ubuntu-latest
    needs: buildPython
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Check Download
        run: ls -lah dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
