name: Publish PyPI Package

on:
  workflow_call:
    secrets:
      pypi_token:
        required: true

jobs:
  publishPython:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: cargo

      - uses: actions/download-artifact@v3
        with:
          name: pydantic-schema
          path: packages/python/src/lcax

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Dependencies
        run: |
          pip install maturin virtualenv
          virtualenv venv
          source venv/bin/activate
          maturin develop --target x86_64-unknown-linux-gnu

      - name: Publish to PyPI
        run: |
          source venv/bin/activate
          maturin publish --out dist
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.pypi_token }}