name: Publish PyPI Package

on:
  workflow_call:
    secrets:
      pypi_token:
        required: true
    inputs:
      release_version:
        required: false
        type: string
        default: ""

jobs:
  publishPython:
    if: ${{ inputs.release_version != ''}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: cargo

      - uses: actions/download-artifact@v4
        with:
          name: pydantic-schema
          path: packages/python/src/lcax

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Dependencies
        run: |
          pip install maturin virtualenv
          virtualenv venv
          source venv/bin/activate
          maturin develop --target x86_64-unknown-linux-gnu

      - name: Publish to PyPI
        run: |
          source venv/bin/activate
          maturin publish --out dist
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.pypi_token }}