
name: Publish NPM Package

on:
  workflow_call:
    inputs:
      release_version:
        type: string
        default: ""
        required: true
    secrets:
      npm_token:
        required: true

env:
  NODE_VERSION: '20.x'

jobs:
  publishJavaScript:
    if: ${{ inputs.release_version != ''}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: cargo

      - uses: jetli/wasm-pack-action@v0.4.0

      - name: Build
        run: wasm-pack build --features jsbindings

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Publish
        working-directory: pkg
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}