name: Publish PyPI Package

on:
  workflow_call:
    secrets:
      pypi_token:
        required: true

jobs:
  publishPython:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: cargo

      - uses: actions/download-artifact@v3
        with:
          name: pydantic-schema
          path: packages/python/src/lcax/pydantic.py

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Dependencies
        run: |
          pip install maturin virtualenv

      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.pypi_token }}
        with:
          command: publish
          args: --out dist
          manylinux: auto
